server:
  port: 8004

spring:
  application:
    name: cloud-paymentzk-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://mysql.cchu.me:3306/sc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cchu
    password: HAVO7dpkunQ0
  cloud:
    zookeeper:
      connect-string:  zk.cchu.me:2181
