server:
  port: 8004

spring:
  application:
    name: cloud-paymentzk-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://10.196.22.59:3306/sc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 23nNswca
  cloud:
    zookeeper:
      connect-string:  192.168.31.156:2181
